### ISSUE TITLE
Setup removes wireless networks!

### ISSUE THREAD

**Issue by PrieureDeSion** [clearpathrobotics/ros_computer_setup#18]
Hi!

I had to recently set up the TX2 on my Jackal for updating the jetpack and am having trouble with the WiFi since. WiFi works perfectly before I run the ros_computer_setup script and right after doing that, the WiFi stops working. The device is not detected and there is absolutely nothing I could do to revive it. Any leads would be appreciated!

Update: I noticed that this is because the setup uses `wicd` and disables NetworkManager. Navigating your way around `wicd-curses` will fix this, but would be nice to have an option/flag to retain the default NetworkManager.

**Comment by civerachb-cpr** [comment]
The setup script installs `wicd`:
https://github.com/clearpathrobotics/ros_computer_setup/blob/90de83bffbe70fb65fdd649f6fe7c17cbbf88199/install.sh#L496

This normally conflicts with the default `network-manager` suite of tools that Ubuntu Desktop uses.  All of our 18.04-based robots use `wicd` for managing the wireless when using standard x64-based PCs.  This script is intended to replicate that.  But I'll see if there's a minimally-disruptive way to add the option to bypass `wicd`.

**Comment by PrieureDeSion** [comment]
Thank you very much for the prompt response and resolution!
