### ISSUE TITLE
Install removes wifi dongle from network devices

### ISSUE THREAD

**Issue by mpitropov** [clearpathrobotics/ros_computer_setup#30]
I'm currently setting up an Xavier NX with a wifi dongle. Usually I've been setting things up with a Xavier AGX and a wifi card.

After running this script the wifi dongle is not shown in `ifconfig` and I can't seem to get wifi working again. Maybe it is the netplan install or autoremove might remove something?

I'm going to make the whole network configuration optional and see if I can have things working that way.

**Comment by tonybaltovski** [comment]
Do you know which driver is being used for the device?   The netplan config doesn't add the wireless devices.  Have you tested prior to the running this script?

**Comment by mpitropov** [comment]
If I run `usb-devices` I find it listed as this with the rtl8xxxu driver:
```
T:  Bus=01 Lev=01 Prnt=01 Port=02 Cnt=01 Dev#=  2 Spd=480 MxCh= 0
D:  Ver= 2.10 Cls=00(>ifc ) Sub=00 Prot=00 MxPS=64 #Cfgs=  1
P:  Vendor=2357 ProdID=0109 Rev=02.00
S:  Manufacturer=Realtek 
S:  Product=802.11n NIC 
S:  SerialNumber=X
C:  #Ifs= 1 Cfg#= 1 Atr=e0 MxPwr=500mA
I:  If#= 0 Alt= 0 #EPs= 5 Cls=ff(vend.) Sub=ff Prot=ff Driver=rtl8xxxu
```

**Comment by mpitropov** [comment]
So my initial test of just putting these lines in a yes/no prompt, did not seem to help. https://github.com/clearpathrobotics/ros_computer_setup/blob/main/install.sh#L502-L554

The driver is gone after running the script:
```
T:  Bus=01 Lev=01 Prnt=01 Port=02 Cnt=01 Dev#=  3 Spd=480 MxCh= 0
D:  Ver= 2.10 Cls=00(>ifc ) Sub=00 Prot=00 MxPS=64 #Cfgs=  1
P:  Vendor=2357 ProdID=0109 Rev=02.00
S:  Manufacturer=Realtek
S:  Product=802.11n WLAN Adapter
C:  #Ifs= 1 Cfg#= 1 Atr=e0 MxPwr=500mA
I:  If#= 0 Alt= 0 #EPs= 5 Cls=ff(vend.) Sub=ff Prot=ff Driver=(none)
```

**Comment by tonybaltovski** [comment]
Is there anything in `/etc/rc.local`? Does manually loading the driver using `sudo modprobe rtl8xxxu`?

**Comment by mpitropov** [comment]
I commented out the whole bluetooth, network configuration and autoremove sections and it didn't remove the driver. The WiFi dongle I was testing with only supports 2.4 GHz so I'm going to switch to a different one next week and try things out again.

**Comment by mpitropov** [comment]
The new [WiFi dongle](https://www.alfa.com.tw/products/awus036acm?variant=39477234597960) we purchased does not support the kernel version that is installed with "JetPack version 4.6.2". I tried to instead install "Jetpack 5.1 (rev 1." and when I entered "y" to reboot at the end of the script, it went straight to recovery mode. I couldn't ssh into it. Is that version not supported?
