### ISSUE TITLE
How does the Jackal wifi light get set?

### ISSUE THREAD

**Issue by mpitropov** [clearpathrobotics/ros_computer_setup#31]
The jackal wifi light is off on my latest install.

I noticed the `JACKAL_WIRELESS_INTERFACE` was removed from last MR. https://github.com/clearpathrobotics/ros_computer_setup/pull/28/files#diff-043df5bdbf6639d7a77e1d44c5226fd7371e5259a1e4df3a0dd5d64c30dca44fL481

How does the wifi light get set currently?

**Comment by tonybaltovski** [comment]
It would be you manually setting based on the wireless interface.  It was removed since this was supposed to be added to the jackal as well: https://github.com/dingo-cpr/dingo_robot/blob/noetic-devel/dingo_bringup/scripts/set-wireless-interface.  I will add shortly.

**Comment by tonybaltovski** [comment]
PR pending review here: https://github.com/jackal/jackal_robot/pull/69
